# web/Dockerfile.web
FROM nginx:alpine

# Создаем директории
RUN mkdir -p /usr/share/nginx/html/js /usr/share/nginx/html/css

# Копируем ВСЕ статические файлы
COPY ./web/public/ /usr/share/nginx/html/
COPY ./web/js/ /usr/share/nginx/html/js/

# Конфигурация nginx
COPY ./web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]